version: '3.4'

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        waitForContainer: database:1234

  database:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
        SA_PASSWORD: "P@ssW0rd!"
        ACCEPT_EULA: "Y"
    ports:
      - "1234:1433"